name: build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: apt-get
        run: |
          sudo apt install build-essential git gfortran liblapack-dev libgsl-dev minpack-dev f2c jhead zlib1g-dev libjpeg62-dev libceres-dev cmake

      - name: clone vlfeat
        run: git clone https://github.com/vlfeat/vlfeat.git

      - name: compile vlfeat
        run: |
          cd vlfeat
          sed -i 's/  if(! (max_value >= 65536)) {/  if(! max_value >= 65536) {/' vl/pgm.c
          make

      - name: clone bundler
        run: git clone https://github.com/snavely/bundler_sfm.git

      - name: compile bundler
        run: |
          cd bundler_sfm
          sed -i 's/# USE_CERES=true/USE_CERES=true/' src/Makefile
          make

      - name: remove files
        run: |
          cd bundler_sfm/bin
          rm zlib1.dll
          rm ToSift.sh
          rm ToSiftList.sh
          rm extract_focal.pl

      - name: clone cmvs-pmvs
        run: git clone https://github.com/pmoulon/CMVS-PMVS.git

      - name: compile cmvs-pmvs
        run: |
          cd CMVS-PMVS/program
          mkdir build; cd build
          cmake -g "CodeBlocks - Unix Makefiles" ..
          make

      - name: prepare files
        run: |
          cp vlfeat/bin/glnxa64/sift bundler_sfm/bin
          cp vlfeat/bin/glnxa64/libvl.so bundler_sfm/bin
          cp CMVS-PMVS/program/build/main/cmvs bundler_sfm/bin
          cp CMVS-PMVS/program/build/main/pmvs2 bundler_sfm/bin
          cp CMVS-PMVS/program/build/main/genOption bundler_sfm/bin
                  
          mkdir lpt-ubuntu-18.04
          cp -r bundler_sfm/bin lpt-ubuntu-18.04
          cp Makefile lpt-ubuntu-18.04
          cp LICENSE lpt-ubuntu-18.04
          cp vlfeat/COPYING lpt-ubuntu-18.04/bin 

          cd lpt-ubuntu-18.04
          mkdir lib
          mkdir -p examples/ET
          mkdir -p examples/kermit
          mv bin/libANN_char.so lib
          mv bin/libvl.so lib

          cd ..
          cp -r cfg lpt-ubuntu-18.04
          cp -r utils lpt-ubuntu-18.04
          chmod -R u+x lpt-ubuntu-18.04/bin
          cp bundler_sfm/examples/ET/*.jpg lpt-ubuntu-18.04/examples/ET
          cp bundler_sfm/examples/kermit/*.jpg lpt-ubuntu-18.04/examples/kermit

      - name: tar
        run: |
          tar -zcvf lpt-ubuntu-18.04.tar.gz lpt-ubuntu-18.04

      - name: release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "*.tar.gz"
          release-tag: "latest"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
