name: build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: "contains(toJSON(github.event.commits.*.message), '[build]')"

    steps:
      - uses: actions/checkout@v2

      - name: apt-get
        run: |
          sudo apt install build-essential git gfortran liblapack-dev libgsl-dev minpack-dev f2c jhead zlib1g-dev libjpeg62-dev libceres-dev cmake

      - name: clone bundler
        run: git clone https://github.com/snavely/bundler_sfm.git

      - name: get sift
        run: |
          wget http://www.cs.ubc.ca/~lowe/keypoints/siftDemoV4.zip
          unzip siftDemoV4.zip
          cp siftDemoV4/sift bundler_sfm/bin

      - name: compile bundler
        run: |
          cd bundler_sfm
          sed -i 's/# USE_CERES=true/USE_CERES=true/' src/Makefile
          make

      - name: remove files
        run: |
          cd bundler_sfm/bin
          rm sift
          rm zlib1.dll

      - name: clone cmvs-pmvs
        run: git clone https://github.com/pmoulon/CMVS-PMVS.git

      - name: compile cmvs-pmvs
        run: |
          cd CMVS-PMVS/program
          mkdir build; cd build
          cmake -g "CodeBlocks - Unix Makefiles" ..
          make

      - name: prepare files
        run: |
          cp CMVS-PMVS/program/build/main/cmvs bundler_sfm/bin
          cp CMVS-PMVS/program/build/main/pmvs2 bundler_sfm/bin
          cp CMVS-PMVS/program/build/main/genOption bundler_sfm/bin
          chmod -R u+x bundler_sfm/bin
                  
          mkdir lpt-ubuntu-18.04
          mkdir bundler-ubuntu-18.04
          mkdir cmvs-pmvs-ubuntu-18.04

          cp -r bundler_sfm/bin lpt-ubuntu-18.04
          cp -r bundler_sfm/utils lpt-ubuntu-18.04
          chmod u+x install-sift.sh
          cp install-sift.sh lpt-ubuntu-18.04
          cp Makefile lpt-ubuntu-18.04

          cd lpt-ubuntu-18.04
          mkdir lib
          mkdir -p examples/ET
          mkdir -p examples/kermit
          mv bin/libANN_char.so lib

          cd ..
          cp bundler_sfm/examples/ET/*.jpg lpt-ubuntu-18.04/examples/ET
          cp bundler_sfm/examples/kermit/*.jpg lpt-ubuntu-18.04/examples/kermit

          cp lpt-ubuntu-18.04/bin/cmvs cmvs-pmvs-ubuntu-18.04
          cp lpt-ubuntu-18.04/bin/pmvs2 cmvs-pmvs-ubuntu-18.04
          cp lpt-ubuntu-18.04/bin/genOption cmvs-pmvs-ubuntu-18.04

          cp -r lpt-ubuntu-18.04/bin bundler-ubuntu-18.04
          cp -r lpt-ubuntu-18.04/lib bundler-ubuntu-18.04
          cp -r lpt-ubuntu-18.04/utils bundler-ubuntu-18.04
          rm bundler-ubuntu-18.04/bin/cmvs
          rm bundler-ubuntu-18.04/bin/pmvs2
          rm bundler-ubuntu-18.04/bin/genOption

      - name: tar
        run: |
          tar -zcvf lpt-ubuntu-18.04.tar.gz lpt-ubuntu-18.04
          tar -zcvf bundler-ubuntu-18.04.tar.gz bundler-ubuntu-18.04
          tar -zcvf cmvs-pmvs-ubuntu-18.04.tar.gz cmvs-pmvs-ubuntu-18.04

      - name: release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "*.tar.gz"
          release-tag: "stable"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
